#!/usr/bin/env python3
# gen-env.py
#
# Reads build.yml and writes .env with all resolved paths.
# Called by the Makefile via: python3 gen-env.py build.yml .env
#
# Do not invoke directly — use: make env

import sys
import os
import datetime
import platform


def load_flat(path):
    """
    Parse a simple nested YAML file into a flat dict of dotted keys.
    Supports scalar values only (no lists, no anchors, no multi-line).
    """
    result = {}
    stack = []
    with open(path) as f:
        for line in f:
            s = line.rstrip()
            if not s or s.lstrip().startswith('#'):
                continue
            indent = len(s) - len(s.lstrip())
            if ':' not in s:
                continue
            k, _, v = s.lstrip().partition(':')
            k = k.strip()
            v = v.strip().strip('"').strip("'")
            if ' #' in v:
                v = v[:v.index(' #')].strip().strip('"').strip("'")
            while stack and stack[-1][0] >= indent:
                stack.pop()
            stack.append((indent, k))
            result['.'.join(x[1] for x in stack)] = v
    return result


def resolve(yml, override_key, sdk_derived):
    """Return override value if non-empty, else the SDK-derived default."""
    v = yml.get(override_key, '').strip()
    return v if v else sdk_derived


def main():
    if len(sys.argv) != 3:
        print(f"usage: {sys.argv[0]} <build.yml> <output-.env>", file=sys.stderr)
        sys.exit(1)

    yml_path = sys.argv[1]
    out_path = sys.argv[2]

    yml = load_flat(yml_path)

    sdk_root    = yml.get('sdk.root', '')
    sdk_version = yml.get('sdk.version', '')
    gcc         = yml.get('toolchain.gcc', '')

    # Detect host arch for SDK path selection.
    # This is the build host arch (x86_64 or aarch64), not the cross-compilation
    # target. The cross target is always aarch64 and is handled by arm.cmake.
    machine = platform.machine()
    if machine in ("x86_64", "amd64"):
        sdk_arch = "x86_64"
    elif machine in ("aarch64", "arm64"):
        sdk_arch = "aarch64"
    else:
        print(f"WARNING: unknown host arch '{machine}', defaulting to aarch64 for SDK path", file=sys.stderr)
        sdk_arch = "aarch64"

    sdk_base = f"{sdk_root}/sdk-{sdk_version}/{sdk_arch}"

    mlir_compiler_dir = resolve(yml, 'overrides.mlir_compiler_dir',
                                f"{sdk_base}/compiler")
    toolbox_dir       = resolve(yml, 'overrides.toolbox_dir',
                                f"{sdk_base}/toolbox/build/install-fpga")
    runtime_dir       = resolve(yml, 'overrides.runtime_dir',
                                f"{sdk_base}/fpga/runtime")

    ts = datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')

    lines = [
        f"# AUTOGENERATED by gen-env.py at {ts}",
        f"# Source: build.yml",
        f"#",
        f"# Do not edit by hand — run 'make env' to regenerate.",
        f"# Safe to source into an interactive shell: source .env",
        f"",
        f"SDK_ROOT={sdk_root}",
        f"SDK_VERSION={sdk_version}",
        f"SDK_ARCH={sdk_arch}",
        f"",
        f"MLIR_COMPILER_DIR={mlir_compiler_dir}",
        f"TOOLBOX_DIR={toolbox_dir}",
        f"RUNTIME_DIR={runtime_dir}",
        f"",
        f"CC={gcc}/bin/gcc",
        f"CXX={gcc}/bin/g++",
        f'LD_LIBRARY_PATH={gcc}/lib64${{LD_LIBRARY_PATH:+:${{LD_LIBRARY_PATH}}}}',
    ]

    tmp = out_path + '.tmp'
    with open(tmp, 'w') as f:
        f.write('\n'.join(lines) + '\n')
    os.replace(tmp, out_path)
    print(f"[gen-env] wrote {out_path}")


if __name__ == '__main__':
    main()